(() => {
  // Article overrides: commentHeat 1-5, reaction, visitorClub.
  const seeded = {
    'arsenal-pio-91': [
      ['PioNation','90+1 and he absolutely buries it. That is a striker who does not care what minute it is.'],
      ['NorthBankVisitor','We should have killed this match long before stoppage time. You got one last look and punished us for it.','ARSENAL'],
      ['MeretUnion','Without Meret this is over long before stoppage time. Give the keeper his flowers.'],
      ['GoonerInPeace','Raya spent ninety minutes saving us and somehow your giant striker still ruined the night. I hate this competition.','ARSENAL'],
      ['SaladinoOutNow','I had the post ready. Then Pio scored. Draft deleted.']
    ],
    'bayern-test': [
      ['EuropeanNights','Bayern were cleaner. Learn from it and move.'],
      ['SuedkurveVisitor','Good team. Big ambitions. But when the chances came, you saw what this level actually costs.','BAYERN'],
      ['DaviesExpress','Davies was cooking that left side and nobody finished the meal.'],
      ['MiaSanMiaTalk','Davies can run at us all night. Scoreboard still says 0-2. Welcome to the deep end.','BAYERN'],
      ['NapoliDoomer','PROJECT OVER. I WILL REVERSE THIS TAKE AFTER THE NEXT WIN.']
    ],
    'udinese-pio-clean-sheet': [
      ['PioNation','Seven logged goals and another winner. At some point we can stop calling this a hot streak and admit he is just clinical.'],
      ['BeierDefenseLeague','Back-to-back assists for Beier. Quietly doing a lot of the dirty work around Pio.'],
      ['FriulaniAway','You needed one finish and then parked the gates. Annoying, but we gave Pio far too much room for the goal.','UDINESE'],
      ['curva_bastoni','That back four was disgusting today. Udinese got absolutely nothing for free.']
    ],
    'genoa-drought': [
      ['vesuvio_ultras87','Two straight 0-0s. Somebody please locate the goal.'],
      ['GrifoneOnTour','League leaders came to Marassi and forgot where the net was. Thanks for the point, lads.','GENOA'],
      ['PartenopeiProfessor','Defensive structure excellent. Final-third execution absolutely dead.'],
      ['RossobluNoise','Call it a drought if you want. We call it ninety minutes of making your expensive attack miserable.','GENOA']
    ],
    'lazio-control': [
      ['azzurro_76','A point with that much rotation is not the apocalypse.'],
      ['LazioAwayDays','All that talk about Napoli depth and we still left with the same number of goals as you.','LAZIO'],
      ['NapoliDoomer','WE ARE FINISHED. DELETE THE CLUB.'],
      ['tacticalnonno','Back line good. Midfield fine. Attack had the menace of a damp sock.']
    ],
    'sassuolo-response': [
      ['PazEnjoyer','Paz off the bench and straight into the winner. That is my guy.'],
      ['NeroverdeGuest','We had you wobbling after Bayern and still found a way to throw it away late. Absolutely sickening.','SASSUOLO'],
      ['ChiesaHive','Chiesa dragged us level and Beier finished the job. Proper response.'],
      ['MapeiMouth','If we defend the last ten minutes like adults, half this article does not exist.','SASSUOLO']
    ],
    'chiesa-pisa': [
      ['FedeForever','CHIESA 80TH MINUTE. CINEMA.'],
      ['PisaAway','You were 2-0 up and we still had your stadium panicking at 2-2. Do not pretend this was comfortable.','PISA'],
      ['StachAttack','Goal and assist from Stach and somehow nobody talks about it.'],
      ['NapoliTherapy','This club refuses to win a normal match.']
    ],
    'torino-control': [
      ['EndrickEra','That finish is exactly why Endrick has to keep getting real minutes.'],
      ['GranataGuest','One McTominay pass, one Endrick finish. That was basically the whole difference.','TORINO'],
      ['PeacockWatch','Clean sheet for Peacock. Development game went exactly how you want it to go.']
    ],
    'three-nos': [
      ['KeepTheCore','Two hundred million for Beier, 133.6 for Pio, 43.5 for the captain. Three offers, three noes. That is a club trying to win, not balance a spreadsheet.'],
      ['CuleWindowWatch','Turning down 204 million for Beier is hilarious. Fine. Keep him warm for us. We will ask again.','BARCELONA'],
      ['BeierDefenseLeague','Barcelona could have added another zero and I still would have wanted the club to hang up. He is part of this project.'],
      ['BayernScoutRoom','Rejecting 133.6 for Pio was brave. We were trying to save you the trouble before he became even more expensive.','BAYERN'],
      ['PioNation','Bayern putting that kind of money down this early tells you exactly what we have. Do not even answer the phone next time.'],
      ['RBLVisitor','43.5 for an ageing fullback was a serious offer. Do not act like Leipzig sent a bag of crisps.','RB LEIPZIG'],
      ['CaptainRespect','Kayode can be the future and Di Lorenzo can still matter now. Selling the captain just because the succession plan exists would have been unnecessary.'],
      ['MercatoMadness','The best part is that Napoli did not need the money. Europe called, Napoli said no, and everybody moved on. That is new-money arrogance and I love it.'],
      ['NoSellingAllowed','Beier and Pio both staying after those bids is a bigger statement than another signing would have been.'],
      ['CuleCoping','You are all celebrating a rejected bid like a trophy. We will revisit this conversation when Beier wants a bigger stage.','BARCELONA'],
      ['NapoliSempre','This is the core now. If Europe wants them, Europe can watch them in a Napoli shirt.']
    ],
    'fiorentina-kdb-1-0': [
      ['KDBClock','One point-blank save, then he comes back and finishes the next one. Veteran behaviour.'],
      ['ChiesaHive','Chiesa central after halftime was fun, but that assist before the break was the real damage.'],
      ['MeretUnion','That save changed the entire ending. People will remember the goal; I am remembering the glove.'],
      ['StachAttack','GOAL-LINE CLEARANCE. Put some respect on the insurance policy.'],
      ['ViolaInTransit','Kean had the chance to make this a different story. We did not take it.','FIORENTINA'],
      ['RotationPolice','This is what squad depth is for: win the awkward one and keep the heavy artillery for Europe.']
    ],
    'chelsea-pio-1-0': [
      ['PioNation','Arsenal. Udinese. Chelsea. The boy keeps choosing the loudest possible moment to score.'],
      ['DaviesExpress','That run was absolutely disgusting. He turned a Chelsea attack into a Napoli goal in seconds.'],
      ['MeretUnion','90+1, close range, one-goal lead. That save is worth the same as the goal to me.'],
      ['EndrickEra','Trubin stopping Endrick is the only reason this did not become 2-0. He was dangerous all night.'],
      ['BridgeVisitor','One transition, one finish, then your keeper turns into a wall. Horrible way to lose.','CHELSEA'],
      ['BlueFlagGuest','You lot are going to call this a masterclass for six months. We had chances. Finish one next time, I know.','CHELSEA'],
      ['EuropeanNights','Bayern showed the gap. Arsenal showed the nerve. Chelsea just got the answer.'],
      ['BastoniAgenda','Winning 1-0 away in Europe with your keeper making the last save is proper grown-up football.'],
      ['PioShirtOwner','I am running out of ways to say START PIO.'],
      ['NoTacticsJustVibes','Davies to Pio is becoming a cheat code and I refuse to apologize for enjoying it.'],
      ['LondonAwayEnd','You came for a point and stole all three. Yes I am bitter.','CHELSEA'],
      ['ScudettoOrBust','Now take this exact level of concentration into Inter. No emotional hangover.']
    ],
    'inter-title-race-preview': [
      ['ScudettoOrBust','Four points. Win and it is one. I do not need a motivational speech; I need kickoff.'],
      ['PioNation','If Pio scores against Inter after Arsenal, Udinese and Chelsea, I am becoming completely unreasonable.'],
      ['NerazzurriGuest','Four points clear and somehow this article reads like Napoli are the ones being chased. Come take it from us.','INTER'],
      ['InteristaInPeace','You beat Chelsea. Congratulations. Serie A is a different conversation and we are leading it.','INTER'],
      ['DaviesExpress','Inter cannot let Davies run into open grass. Which means I desperately want them to try.'],
      ['BastoniAgenda','This is the kind of match where Bastoni and Buongiorno can change the title race without touching the scoresheet.'],
      ['CurvaCalculator','Win: one point back. Draw: four. Lose: seven. I have stared at those numbers for twenty minutes.'],
      ['SaladinoOutNow','If we win I never doubted him. If we lose I have seventeen drafts ready.'],
      ['NerazzurriNoise','All this pressure is on you. We can leave with a draw and still wake up four clear.','INTER'],
      ['NoTacticsJustVibes','Nobody say “it is only November.” I have already turned this into a cup final in my head.'],
      ['MidfieldNonno','McTominay has to own the middle. If this becomes a transition circus, I am aging ten years.'],
      ['CaptainRespect','Di Lorenzo off the bench late if we are protecting a lead. I can already see it.']
    ],
    'fixture-run-november': [
      ['CalendarVictim','Inter, Salzburg, Juve, Coppa, Roma, then Juve again. Whoever made this schedule hates sleep.'],
      ['SquadDepthDept','This is where Stach, Chiesa, KDB, Geertruida and the rest stop being “depth” and start being the season.'],
      ['JuveWatcher','One point between us in the league and then a Supercoppa meeting later. Juventus are going to be sick of seeing us.'],
      ['EuropeanNights','Salzburg tucked between league games is exactly the kind of fixture that punishes lazy rotation.'],
      ['CupRomantic','Do not throw the Coppa away just because the league run is heavy. Trophies are trophies.'],
      ['RomaLurker','Everybody is looking at Juventus and Inter. Fine by us.','ROMA']
    ]
  };

  const profiles = {
    'arsenal-pio-91':[5,'big-draw','ARSENAL'], 'bayern-test':[5,'big-loss','BAYERN'],
    'udinese-pio-clean-sheet':[2,'win','UDINESE'], 'genoa-drought':[3,'frustrating-draw','GENOA'],
    'lazio-control':[3,'frustrating-draw','LAZIO'], 'sassuolo-response':[3,'comeback-win','SASSUOLO'],
    'chiesa-pisa':[3,'chaotic-win','PISA'], 'torino-control':[2,'win','TORINO'],
    'italy-pipeline':[3,'big-win','FRANCE'], 'napoli-still-top':[3,'title-race','NONE'],
    'three-nos':[3,'story','NONE'], 'pio-shirt':[2,'story','NONE'], 'paz-kdb':[2,'story','NONE'],
    'peacock-problem':[2,'story','NONE'], 'captain-future':[2,'story','NONE'], 'stach-insurance':[2,'story','NONE'],
    'fiorentina-kdb-1-0':[3,'win','FIORENTINA'], 'chelsea-pio-1-0':[5,'big-win','CHELSEA'],
    'inter-title-race-preview':[5,'rivalry','INTER'], 'fixture-run-november':[4,'title-race','NONE']
  };

  const handles = ['curva_commentator','napoli_in_my_blood','tactical_zio','scapegoat_selector','forza_forever','northstandnoise','partenopei92','matchday_meltdown','bluewall','touchlinelawyer','awayendchaos','vesuvio_voice','SaladinoOutNow','SanPaoloSufferer','ScudettoOrBust','NapoliTherapy','90MinuteNervousBreakdown','TransferListEveryone','ActuallyWatchTheGame','NoTacticsJustVibes','PioNation','MeretUnion','DaviesExpress','BastoniAgenda','KDBClock','ChiesaHive','EndrickEra','PazEnjoyer','BeierDefenseLeague','StachAttack','CaptainRespect','CurvaCalculator','MidfieldNonno','RotationPolice','CalendarVictim','SquadDepthDept','EuropeanNights','CupRomantic','TitleRaceInsomnia','BlueSideNaples','VesuviusPress','PartenopeiProfessor','SouthStandAnalyst','AwayDayNapoli','NapoliSinceBirth','OneNilEnjoyer','CleanSheetCult','LateGoalTrauma','MercatoMadness','NoSellingAllowed','SecondBallMerchant','PressingTruther','LowBlockSurvivor','SetPiecePanic','HalftimeOverthinker','BenchCamEnjoyer','FiveMinuteAddedTime','VARConspiracyDesk','ExpectedGoalsHater','SundayNightScaries'];
  const rivalHandles = ['AwayEndTourist','OppositionScout','ScoreboardMerchant','HereForTheMeltdown','VisitingNoise','WrongEndOfTown','RivalAccount','AwayDayLurker','NeutralButNotReally','TableScreenshotter','GuestSection','RivalWithReceipts','AwayEndLawyer','OppositionTherapy','VisitingTactico','ScorelineEnjoyer','CommentSectionInvader','NotYourFriend','RivalHistorian','AwayFanOnWifi','TunnelCamGuest','LastWordMerchant','AwayDayAccount','VisitingProfessor'];
  const targetByHeat = {1:8,2:12,3:18,4:26,5:34};
  const knownClubs = ['CHELSEA','ARSENAL','BAYERN','INTER','MILAN','JUVENTUS','ROMA','LAZIO','GENOA','TORINO','FIORENTINA','PISA','SASSUOLO','UDINESE','BARCELONA','REAL MADRID','RB LEIPZIG','FRANCE'];
  const bigNames = ['CHELSEA','ARSENAL','BAYERN','INTER','MILAN','JUVENTUS','BARCELONA','REAL MADRID','MANCHESTER CITY','LIVERPOOL','PSG','FRANCE'];

  const banks = {
    win:['Three points. Clean enough. Nobody needs a documentary about it.','Good teams win these without turning every match into a crisis meeting.','Bank it and move. The schedule is too ugly to complain about winning.','Not every win needs fireworks. Sometimes you just take the points and go home.','I will take boring wins until the trophy cabinet physically runs out of space.','The best thing about this result is how quickly we can stop talking about it and prepare for the next one.','One goal was enough because the back line treated the box like private property.','Professional is not an insult. Professional wins titles.','There was a version of this game where we got impatient and made it stupid. We did not.','The scoreboard is doing exactly what I asked of it.','If you can win without spending every emotional resource in the squad, that matters.','This team is learning how to make 1-0 feel normal.','Take the clean sheet, take the points, ignore the people demanding five goals every weekend.','Some wins are statements. Some are receipts. This one is just useful, and useful is good.','No chaos tax tonight. I could get used to this.','The closing phase was ugly in the correct way.','You can tell the squad believes one goal can be enough now.','Three points with something left in the legs is a beautiful sentence.','That is a grown-up result, even if nobody puts it in a montage.','We did not dominate every minute. We dominated the only number that matters.'],
    'comeback-win':['I aged nine years and somehow we got three points. Completely normal Napoli experience.','The moment we went behind I knew this thread would become a crime scene. Credit for dragging it back.','I had three different scapegoats selected and then we won. Annoying.','That is the kind of win that makes the dressing room louder than the tactics board.','Going behind used to feel terminal. Now it just feels like the start of the second act.','I would like to file a complaint about the route we took to three points.','The bench changed the match and that is exactly what a deep squad is supposed to do.','Every comeback makes the next one easier to believe in. That matters.','I was furious for an hour and ecstatic for ten minutes. Football remains a terrible hobby.','The response after conceding was the best part. Nobody hid.','You can coach shape. You cannot fake a team that believes it can rescue a match.','Please stop testing my cardiovascular system just to prove the mentality is good.','The first half thread and the full-time thread should be preserved as evidence of mass hysteria.','Credit where it is due: the staff got the changes right.','That winner felt inevitable for exactly thirty seconds, which is enough for me.','The emotional swing in here could power the city.','That is two points rescued by nerve and one earned by quality.','Comebacks are fun after they are over. During them I am filing legal documents.'],
    'chaotic-win':['We won and I am still angry. That should tell you everything.','Three points secured, blood pressure destroyed.','Please win one match like adults. I am begging.','The final whistle is doing a lot of work for the mood in here.','This club has mistaken entertainment for a legal obligation.','I refuse to analyze a match that tried to kill me personally.','At no point did I feel safe, including after the final whistle.','The defending will be discussed tomorrow. Tonight I am taking the points and disappearing.','How can a victory feel like an incident report?','Somebody check on the coaching staff. Nobody survives these games forever.','I celebrated the winner and immediately started worrying about the restart.','There were at least four separate moments where the match should have been over.','This team can turn a routine evening into prestige television.','The good news: three points. The bad news: everything between kickoff and full time.','I need the next match to be 2-0 and boring by minute sixty.','Nobody won tactically. Napoli just survived the plot.','I am not rewatching this. I know what happened and I reject it.','Chaos merchants, all of them.'],
    draw:['A point is a point, but nobody is framing this performance.','Not a disaster. Not exactly something I want to watch twice either.','The unbeaten column is doing some heavy lifting for my mood tonight.','There are draws you accept and draws that follow you into the shower.','If the finishing was five percent cleaner we are having a completely different conversation.','I am trying very hard to be normal about one point.','The structure was fine. The last action kept dying.','Nobody panic, but somebody please locate the shooting boots.','It feels worse because the game was there to be taken.','A clean sheet keeps me from becoming fully irrational.','Fine result in isolation. Annoying result in context.','We did enough not to lose and not enough to deserve the dramatic music.','I can live with the point. I cannot love it.','The table will tell us later whether this was useful or expensive.','Ninety minutes of almost.'],
    'frustrating-draw':['I know we did not lose. My nervous system does not care.','Another ninety minutes of passing around the box like there is a force field over the goal.','Somebody explain how a team this talented can make scoring look like advanced physics.','I am not calling it a crisis. I am also absolutely opening the crisis folder.','Zero goals again and somehow I am expected to act normal tomorrow.','The clean sheet is lovely. I would also like to experience a goal before retirement.','Every attack ended one pass before something useful happened.','The defenders deserve overtime pay for carrying the emotional burden of this attack.','We keep reaching the final third and then behaving like the net is protected by lasers.','I have seen enough cutbacks to last a lifetime. Shoot the ball.','This is not panic. This is concentrated irritation.','The worst part is we never looked completely out of control. We just looked unable to finish the sentence.','If we draw 0-0 again I am learning a different sport.','Somebody put a striker in the six-yard box and forbid philosophical debate.','The xG crowd and the eye-test crowd are both miserable tonight. Unity.','There were good patterns. I am begging those patterns to eventually include a goal.','I would like to unsubscribe from sterile control.','The next training session should just be shooting until the sun goes down.','One goal would have changed the entire mood around this place.','Defensively serious, offensively allergic to closure.'],
    'big-draw':['THAT is why you play to the final whistle. Europe can keep the pretty narratives; give me the point.','I was already writing the post-mortem and then the stadium exploded.','A draw has no business feeling this much like a win but here we are.','These are the nights where a team starts believing it belongs with the heavyweights.','If that goal happens in a knockout tie I may actually leave my body.','Pio just turned ninety minutes of suffering into a result we will remember all year.','The equalizer did more than save a point. It changed the temperature around this team.','Elite teams hate opponents who refuse to accept the script.','I had already accepted the loss and apparently the players had not. Good for them.','This is why stoppage time is a public-health issue.','One chance, one finish, one completely different week.','The reaction at the end tells you the dressing room knows what that point meant.','I will not hear “just a draw” from anyone who watched the last ten minutes.','There is a version of this season where that late goal becomes a reference point.','That was resilience with a pulse rate of 190.','We spent eighty-nine minutes learning and one minute refusing to lose.','The point matters. The belief might matter more.','I have watched the goal six times and the night is still young.','Europe is about surviving bad spells long enough to create one moment. We finally did it.','That finish belongs in the season trailer.','I am exhausted and we did not even win.','The away fans are going to hear about that equalizer for years.','This is the kind of draw that ruins the other team’s sleep.','Nobody left early, right? Right?'],
    loss:['Bad night. Own it, fix it, do not let it become two bad nights.','The performance was not catastrophic. The result still sucks.','Nobody gets protected from criticism after a loss, but the season is not on fire.','I can handle losing. I hate losing the same duel twelve times.','There were warning signs before the goal and we ignored every one of them.','The response matters more than the funeral posts in this thread.','Do not overcorrect. Fix the actual problem.','The result is annoying because the match never felt impossible.','Sometimes you get beaten. The next ninety minutes tell you what kind of team you are.','There is plenty to criticize without pretending the project ended tonight.','No excuses, no catastrophe language, just work.','The margins were small and we were on the wrong side of all of them.','I would like one loss where this forum does not attempt a constitutional crisis.','Take the lesson and keep the season moving.','The bench did not rescue us this time. That happens.','This one will sting more if we carry it into the next match.','I am mad now. Ask me tomorrow and I will probably be reasonable.','Scoreboard says loss. Nothing clever fixes that.'],
    'big-loss':['Europe does not care how good the domestic form looks. Miss your chances and elite teams punish you.','I can accept losing to a giant. I cannot accept looking surprised when the level rises.','This is the match the staff need to keep on the projector all week.','No panic, but no excuses either. We found the ceiling tonight and it hit us in the face.','I swear every Champions League loss makes this forum forget the previous six months of football.','If we want to win this competition eventually, nights like this have to hurt.','The gap was not effort. It was execution. That is both better and worse.','We got into dangerous positions and treated the final action like an optional extra.','This is why elite European teams feel cruel. They do not need ten chances.','You can dominate a spell and still lose the match in two actions. Lesson learned.','I do not want a rebuild. I want sharper decisions under pressure.','The opponent did not overwhelm us for ninety minutes. They simply punished every mistake that mattered.','There is no shame in learning the level. There is shame in refusing to learn it.','The scoreline will look worse than some of the football, but the scoreline is what Europe remembers.','We were competitive until the moments that decide elite matches. Unfortunately those are the moments that count.','I am filing this under painful but useful.','The next big European night needs to look different because of this one.','Every title team has a night where the standard gets explained to them. Consider it explained.','They were calmer in both boxes. That is the whole story.','Nobody needs to be sold because of this. Several people need to be better.','If the staff wanted a measuring stick, congratulations, it came with teeth.','The worst response would be pretending the performance was either brilliant or hopeless. It was neither.','We belonged in the game. We did not belong on the scoreboard.','I hate educational losses. Unfortunately this one was educational.'],
    'big-win':['PRINT THE SCOREBOARD AND SEND IT TO EVERYONE WHO TALKED THIS WEEK.','Big game, big pressure, big response. That is what serious teams do.','I will be unbearable until the next kickoff and nobody can stop me.','All week we heard why they were supposed to expose us. Quiet now, is it?','This is the kind of result you bring up completely unprompted for the next five years.','That was not pretty for ninety minutes. It was better: it was controlled under pressure.','You do not need to dominate a heavyweight. You need to beat them.','The keeper, the back line, the transition, the finish. Every department signed the same document tonight.','This is the result that makes the rest of Europe actually read the team sheet.','One-nil against elite opposition hits differently when the last save comes in stoppage time.','The maturity in the final twenty minutes was ridiculous.','I am trying not to overreact, so naturally I have us winning everything.','These are the nights that turn a good season into a story.','The opponent had pressure. Napoli had the moment. That is elite football.','The clean sheet is almost as satisfying as the goal. Almost.','If you want to be taken seriously in Europe, collect serious scalps. Done.','The best part is nobody looked shocked at full time. They looked like they expected to survive it.','That result travels. Every future opponent sees it.','We did not blink. That is the headline.','Somebody update the “can they do it against elite teams” folder.','The away end deserves a documentary after that one.','This is why you protect your best players for the big night.','One chance can change a match when the striker believes before everyone else does.','We got pushed back, adapted, and still carried threat. That is not luck.','The final whistle sounded like a declaration.','I have no constructive criticism at this time. Please respect my privacy.','This team has discovered how much fun suffering can be when you win at the end.','Big nights require big personalities. We had several.','That is a result you use to recruit players in January.','Keep the footage. We will need it for the season review.'],
    rivalry:['I do not care about form, xG, weather or the alignment of the planets. Win the rivalry match.','There are three points and then there are THESE three points.','If we lose this one I am muting every football account for a week.','Nobody say calm down. This fixture is not for calm people.','I have been pretending this is just another match and nobody believes me.','The table makes it important. The badge makes it personal.','Do not chase the game in minute twelve because the crowd is loud. Make them chase us later.','This is exactly why you build a deep squad: so the best eleven can play the matches that change the mood of a season.','I want control for sixty minutes and violence in transition for thirty. Is that too much to ask?','The first tackle is going to tell us what kind of evening this is.','I have no interest in moral victories here.','If we score first, make them feel every second after it.','The manager can save the rotation experiments for literally any other day.','I need the midfield to play like the result personally offended them.','Some fixtures are tactical problems. Some are emotional events with tactics attached.','Please do not give me a red card in the first half. That is my only humble request.','The comments are already unbearable and the ball has not moved yet.','This is where captains matter. Slow it down when it gets stupid.','Win the duels, win the second balls, then let the talent talk.','I do not need a classic. I need three points.','The loser is going to hear about this until the rematch.','Every neutral suddenly has an opinion. Excellent, exactly what we needed.','I have checked the table fourteen times. It has not changed.','This is the first match on the calendar I circled twice.','No cheap goals. Make them earn everything.','If it is 0-0 at halftime, nobody panic. The match will open.','I want the full-strength XI and the full-strength attitude.','This is not the day for “good enough.”'],
    'title-race':['Every dropped point is now a national emergency apparently. Welcome to a title race.','Screenshot the table if you want. Just keep winning.','The only thing worse than being in a title race is not being in one.','I have started doing points projections in October. Someone confiscate my phone.','One point here, two points there, and suddenly every substitution feels like fiscal policy.','The table is close enough that goal difference has entered my nightmares.','This is the stretch where depth turns into points.','We cannot control the other contenders. We can make sure they keep seeing us in the mirror.','Every “routine” league game now carries a little bit of poison.','Do not spend all week watching the table. Win and make them watch us.','The title race is too tight for emotional hangovers after Europe.','One injury can change the whole conversation. Manage the minutes.','I miss September when points felt like points instead of court evidence.','The contenders are close enough that nobody gets to have a bad month.','This is why those ugly 1-0 wins matter in May.','The league is becoming a weekly stress test.','Every rival fan is suddenly doing our fixture math for us.','I do not want to peak in November. I do want to stop donating points.','The next six games will tell us more than the first ten did.','A title race is just a long argument with a spreadsheet.','If we stay within touching distance, the pressure works both ways.','There is no perfect run. There just cannot be a collapse.','Win the home games, survive the ugly away ones, and make the big six-pointers count.','The table is crowded enough that nobody has permission to relax.','I am already calculating what a draw means three fixtures from now. This is unhealthy.','The margins are tiny and the calendar is not helping.','One good week can change everything. One bad week can also change everything. Great sport.','Do not let the race become bigger than the next match.'],
    story:['The squad context matters more than people are admitting.','One player is about to get blamed for all eleven positions and somehow I already know who.','Some of you read the headline and formed a complete tactical thesis.','Give it two weeks and everyone will pretend they always had the correct opinion.','There is a sensible football discussion here, which means the comments will avoid it completely.','I need three more matches before I am willing to pretend I know what this means.','The interesting part is not the headline. It is what this changes in the rotation.','Half the fanbase wants patience and the other half wants a transfer before breakfast.','This is exactly the kind of story that looks obvious only after it works.','The staff have clearly made a decision. Now the player has to justify it.','I am bookmarking this thread because somebody is going to look ridiculous later, possibly me.','Context is doing a lot of work here and that is fine. Football has context.','There are worse problems than having too many good players asking for minutes.','This squad has enough talent that every choice creates a new debate.','I would like to hear the dressing-room version of this story, not the polite public one.','Somewhere an agent is absolutely loving this article.','The next contract conversation just got more expensive.','This is why squad building is never finished even when the window closes.','There is a football answer and a fan answer. They are not currently the same answer.','I am choosing to overreact in a positive direction.','This is the sort of thing that becomes a subplot for three months.','I trust the plan right up until the first bad result, as tradition demands.','The numbers matter, but the role matters more.','Nobody agrees on the hierarchy and that might actually be healthy.','This would be much easier if every player politely accepted being rotation.','I love that the club has problems created by abundance instead of absence.','We are one injury away from everyone pretending this debate never happened.','The article is calm. The group chat is not.','This is not a crisis. It is content.','I need the next press conference immediately.','Football fans can turn a depth chart into a constitutional convention.','The answer probably changes depending on the opponent, which is boring but true.','I am ready to be wrong with confidence.','This story has at least three future comment-section wars in it.','No matter what happens, someone will quote this thread in January.'],
    'upset-loss':['SALADINO OUT. Do not show me the table. Do not show me the form. Explain THIS result.','TRANSFER LIST EVERYONE. I will calm down tomorrow and reject all the offers, but tonight EVERYONE.','No tactical analysis tonight. Just shame. Pure, concentrated shame.','How are we this expensive, this highly rated, and losing THIS match? I need a congressional inquiry.','I defended this project for MONTHS and this is the thanks I get?','Open training tomorrow. No music. No rondos. Just running until somebody apologizes.','I have deleted the game out of solidarity. See you at kickoff next week.','If anybody needs me I will be staring at the ceiling in complete silence.','The entire rival internet is going to use this scoreline against us for six months. Fantastic.','Saladino has twenty-four hours to explain this result to my mother personally.','I am outside the training ground with a PowerPoint and several extremely unreasonable demands.','Bench the starters. Start the academy. Sack the chef. I am not thinking rationally and I refuse to start now.','This team made me believe and THIS is what they do with that trust. Football is a scam.','Cancel recovery. We are reviewing the tape until morale improves.','I have changed my profile picture to a black square. Respect my grief.','Every player should have to read this thread out loud tomorrow morning.','Do not send me possession. Do not send me shots. Send me an explanation.','I am checking the transfer list like it is an emergency exit.','We have achieved the rare result where every rival fan is online at the same time.','I want refunds for minutes I did not personally pay for.','The tactical board should be entered into evidence.','Somewhere a rival account is making a compilation and I can feel it happening.','I am not angry at one player. I am innovating new forms of collective blame.','The next person who says “long season” is getting muted.','I believed in squad depth. Apparently the depth was emotional.','I would like to apologize to everyone I mocked last week. Temporarily.','This is why nobody lets us enjoy anything.','The players owe the badge, the fans, and specifically me a response.','I have started a notes app titled “questions for the manager” and it is already six pages.','The group chat has become a tribunal.','One bad result is not a crisis. This specific bad result is applying for crisis status.','I am inventing punishments that violate several labour laws.','Put the next match on now. I cannot sit with this for a week.','Everybody gets a 3/10 except the bus driver.','I am going to bed furious and waking up with a tactical thread.','This is the kind of result that makes you inspect the difficulty settings.','I have no solutions, only volume.','The rival fans are typing and I can hear the keyboards from here.','We better win the next match 4-0 or I will remain deeply unreasonable.','The season is not over, but my evening absolutely is.']
  };

  const rivalPreview = ['Big article for a match you have not won yet. We will be back here after full time.','You are doing table math already. We are just planning to take the points.','All this confidence before kickoff is exactly why away fans keep screenshots.','Respect the buildup. Ignore the conclusion you already wrote for yourselves.','Your forum has selected the hero, the score and the celebration. Convenient.','We have read the “statement game” speech too. See you on the pitch.','Nothing funnier than rival fans treating a preview like a victory parade.','Keep talking about momentum. Momentum does not mark runners.','You think the pressure is on us. We think the pressure is on you. Perfect.','I came here for scouting and stayed for the confidence levels.','Save a few takes for after the first twenty minutes.','The table is real. So is the match you still have to play.','Your best XI is expected? Good. No excuses either way then.','I love pre-match forums. Everybody is undefeated in theory.','One early goal and this entire thread changes personality.','We are not coming to participate in your storyline.','The louder the preview, the better the receipts.','Please keep the “must win” energy. It makes every misplaced pass funnier.'];
  const rivalGloat = ['Before kickoff your forum was asking how many. After full time it is asking how. Beautiful.','All that depth, all that money, all those ratings, and you still have to read comments from us tonight.','Screenshot the table again. We will screenshot the score.','Your excuses are loading faster than your attack did.','We were told this was supposed to be a routine night for Napoli. Please continue the explanation.','Safe trip home. Bring the possession stats with you if they make you feel better.','I was promised a Napoli statement. I suppose this is technically a statement.','Do not delete the preview article. We need it for archival purposes.','Your comment section was louder before kickoff. Strange.','Turns out “full strength” is not a scoreline.','I came for the meltdown and you have not disappointed.','The tactical excuses are excellent. Please continue.','Nothing personal. I just plan to mention this result in every unrelated conversation.','We will take the points and leave you the expected goals.','The funniest part is how confident the first fifteen minutes of this thread were.','You can call it a bad night. We are calling it our favourite night.','I have already saved three screenshots. Thank you for the content.','Your next-match bounce-back article is going to be incredible.'];
  const rivalExcuse = ['Enjoy the win. We will see how loud this place is when the rematch comes around.','One result and suddenly every Napoli account has discovered dynasty language. Relax.','Fine margins. You took yours, we did not. Do not turn it into a documentary.','You deserved the result. I still reserve the right to be deeply annoying about it.','Congratulations. I will now spend the evening explaining why this match actually did not count.','One goal and one keeper save. Fine. I hate it, but fine.','You got the moment. We got the long walk back to our forum.','I refuse to compliment you more than once, so use it wisely: deserved.','Your striker took the chance. Ours did not. Football remains deeply irritating.','The rematch is already in my calendar.','Do not mistake my presence here for respect. It is mostly anger.','I have several excuses available and I am deciding which one tests best.','You were more clinical. I hate simple explanations.','I will be pretending the referee caused this until further notice.','Take the result. Leave the victory-lap thread where I can avoid it.','I came here ready to gloat and now I have to type “fair play.” Disgusting.','This is a temporary setback in my completely unbiased worldview.','I will concede the match, not the argument.'];
  const rivalDraw = ['You are celebrating a draw like a trophy and I would mock you harder if I was not furious about how it happened.','We had the match in our hands and somehow your forum is the happy one. Disgusting sport.','Take your point. We are taking the screenshots of the celebration.','I came here to gloat and now I have to pretend a draw was part of the plan.','A late equalizer should be illegal when it happens to my club.','Fine. One point each. I still feel like we lost.','Your striker ruined an otherwise excellent evening.','I was drafting jokes and then you scored. This sport has no respect for content creators.','Enjoy the emotional victory. I will cling to the actual draw.','Nobody in our away end is speaking right now. Thanks for that.','We should have killed the game. You made sure we remember it.','I hate that your fans get to leave happier after the same result.','The scoreboard says draw. My mood says robbery.','Next time please equalize earlier so I can emotionally prepare.','One lapse and suddenly your whole forum has discovered religion.','I am blaming added time because blaming ourselves is less fun.'];

  const topicBanks = {
    PIO:['Pio keeps making the striker debate shorter every week.','At some point “form” becomes “this is just who he is.”','The movement before the finish is what keeps getting me. He expects the chance.','Big moments keep finding Pio because Pio keeps arriving in big moments.','Every goal makes that rejected Bayern money look funnier.','The shirt is starting to look less borrowed and more owned.','He is developing faster than the fanbase can update its expectations.','You can see defenders starting to treat him like the first problem on the team sheet.','The best strikers make one chance feel like enough. He is learning that language.','I am no longer asking whether Pio starts. I am asking who starts with him.'],
    MERET:['Meret has quietly turned several one-goal games into three points.','Goalkeeper discourse disappears when the keeper simply keeps saving the season.','That is another result with Meret fingerprints all over it.','He does not need ten saves if the one he makes is the one that matters.','The back line trusts him and you can see it in how aggressively they defend.','Clutch goalkeeping is a real thing and I am collecting evidence.','Every time the match gets desperate, Meret looks calmer.','A save in stoppage time counts as an assist in my heart.'],
    DAVIES:['Davies in transition is basically a tactical emergency for the other team.','The first three steps from Davies change the geometry of the entire pitch.','Stop asking whether he is a winger or a fullback. He is an event.','When there is grass ahead of him, the whole stadium knows what is coming and it still happens.','That left side is not a position anymore. It is Davies territory.','His value is not just the final ball. It is the panic he creates before it.','The opponent can defend the pattern and still lose to the acceleration.','I need one camera angle that shows how quickly the defense starts retreating when he turns.'],
    KDB:['KDB does not need ninety minutes to change the rhythm of a match.','The legs may be older. The pass is still operating on a different timeline.','Every KDB cameo feels like somebody changed the game speed.','There is still nobody else in the squad who sees the first-time pass quite like that.','Veteran minutes are useful when the veteran is Kevin De Bruyne.','He can spend ten minutes quiet and then create the only opening that matters.'],
    CHIESA:['Chiesa remains pure chaos in human form and I mean that as a compliment.','He can look disconnected for ten minutes and then decide the match in one action.','Every squad needs one attacker who treats structure as a suggestion.','Chiesa off the bench changes the emotional temperature immediately.','You can never fully game-plan the nonsense he is about to attempt.','The end product is coming often enough that the chaos is worth it.'],
    ENDRICK:['Endrick keeps making the “rotation player” label harder to defend.','Give Endrick space on the weak side and bad things happen quickly.','His directness is exactly what this attack needs when possession gets too polite.','Every appearance adds another argument for serious minutes.','He does not need to dominate touches to dominate a sequence.','The wing role is starting to make a lot of sense for him.'],
    BASTONI:['Bastoni makes difficult defending look like paperwork.','A 90-rated center back should feel like a luxury. Right now he feels necessary.','The calmest player on the pitch is often the one dealing with the most dangerous situations.','If this team wins something big, Bastoni is going to be all over the footage.','He is playing like the back line belongs to him.','Every elite opponent is another chapter in the legacy conversation.'],
    BUONGIORNO:['Buongiorno at 87 next to Bastoni is starting to look unfair domestically.','The new contract makes more sense every time he wins another ugly duel.','He does the unfashionable defending that lets everyone else look elegant.','That center-back pairing is becoming the floor of this team.','Crucial role, crucial player. The contract conversation was easy for a reason.','He looks exactly like a defender entering his prime should look.'],
    PAZ:['Paz is being asked to learn at Champions League speed. That will either harden him or expose him. So far, so good.','The best thing about Paz is that he does not need the game built around him to matter.','Every big start is another little piece of the succession plan becoming real.','He is not KDB and should not be asked to cosplay as KDB. Let him become his own player.','The versatility is turning into real tactical value.','There are still rough edges, which is normal for someone being trusted this much this early.'],
    BEIER:['Beier does so much connecting work that the goals column undersells him.','The assists are starting to explain why the staff keep trusting Beier.','He makes Pio easier to play with, and that matters.','A forward who can score and make the other striker better is not a problem to solve.','The rejected Barcelona bid keeps aging in interesting ways.','He does not need to be the headline every week to be central to the attack.']
  };

  const h = value => String(value||'').split('').reduce((n,c)=>(n*33+c.charCodeAt(0))>>>0,5381);
  const esc = (v='') => String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  const textOf = a => `${a?.headline||''} ${a?.dek||''} ${(a?.body||[]).join(' ')} ${a?.date||''}`;
  const isPreview = a => /preview|ahead of|next|upcoming/i.test(`${a?.category||''} ${a?.label||''} ${a?.date||''}`);

  function inferVisitor(a){ const u=textOf(a).toUpperCase(); return knownClubs.find(x=>u.includes(x))||''; }
  function inferHeat(a){
    const u=textOf(a).toUpperCase(); let heat=2;
    if(/CHAMPIONS LEAGUE|\bUCL\b|EUROPE|TITLE|SCUDETTO|DERBY|RIVAL|SUPERCOPPA/.test(u)) heat=3;
    if(bigNames.some(x=>u.includes(x))) heat=Math.max(heat,4);
    if(/FINAL|SEMI[- ]?FINAL|QUARTER[- ]?FINAL|KNOCKOUT|TITLE DECIDER|WORLD CUP/.test(u)) heat=5;
    return heat;
  }
  function inferReaction(a){
    const t=textOf(a).toLowerCase(), heat=inferHeat(a);
    if(isPreview(a) && /title|inter|juventus|derby|rival/.test(t)) return 'rivalry';
    if(/upset|stunned|shocked|humiliated|embarrass|relegation|bottom[- ]half/.test(t)&&/loss|defeat|lost|beaten/.test(t)) return 'upset-loss';
    if(/loss|defeat|lost|beaten|0-2|0-3/.test(t)) return heat>=4?'big-loss':'loss';
    if(/draw|level|equaliser|equalizer|0-0|1-1/.test(t)) return heat>=4?'big-draw':'draw';
    if(/comeback|came from behind|late winner/.test(t)) return 'comeback-win';
    if(/win|winner|victory|three points/.test(t)) return heat>=4?'big-win':'win';
    if(/title|scudetto|table|fixtures|schedule/.test(t)) return 'title-race';
    return 'story';
  }
  function profile(a){
    const p=profiles[a.id]||[], reaction=a.reaction||p[1]||inferReaction(a);
    let heat=Number(a.commentHeat||p[0]||inferHeat(a)); heat=Math.max(1,Math.min(5,heat));
    if(reaction==='upset-loss') heat=5;
    const rawVisitor=(a.visitorClub ?? p[2] ?? inferVisitor(a) ?? '');
    const visitor=String(rawVisitor||'').toUpperCase()==='NONE'?'':String(rawVisitor||'').toUpperCase();
    return {heat,reaction,visitor,preview:isPreview(a)};
  }
  function uniquePick(bank,seed,used){
    if(!bank?.length) return null;
    for(let i=0;i<bank.length*3;i++){ const x=bank[(seed+i*7)%bank.length]; if(!used.has(x)) return x; }
    return null;
  }
  function uniqueHandle(bank,seed,used){
    for(let i=0;i<bank.length*3;i++){ const x=bank[(seed+i*5)%bank.length]; if(!used.has(x)) return x; }
    return `${bank[seed%bank.length]}_${seed%997}`;
  }
  function topicsFor(a){
    const u=textOf(a).toUpperCase();
    return Object.entries(topicBanks).filter(([key,bank])=>bank.length&&u.includes(key)).flatMap(([,bank])=>bank);
  }
  function rowsFor(a){
    const p=profile(a), rows=[...(seeded[a.id]||[])], usedText=new Set(rows.map(r=>r[1])), usedHandles=new Set(rows.map(r=>r[0]));
    const seed=h(`${a.id}|${a.headline}|${p.reaction}|${p.heat}`), target=p.reaction==='upset-loss'?42:targetByHeat[p.heat], normal=banks[p.reaction]||banks.story, topics=topicsFor(a);
    let i=0;
    while(rows.length<target&&i<400){
      let visitor='', bank=normal;
      const visitorTurn=p.visitor&&p.heat>=3&&(i%4===1||(p.reaction==='upset-loss'&&i%3===1));
      const topicTurn=topics.length&&i%5===2;
      if(visitorTurn){
        visitor=p.visitor;
        bank=p.preview?rivalPreview:['upset-loss','big-loss','loss'].includes(p.reaction)?rivalGloat:['big-draw','draw','frustrating-draw'].includes(p.reaction)?rivalDraw:rivalExcuse;
      } else if(p.reaction==='upset-loss'&&i%6===4){
        visitor=(seed+i)%2?'INTER':'MILAN'; bank=rivalGloat;
      } else if(topicTurn){
        bank=topics;
      }
      const txt=uniquePick(bank,seed+i*13,usedText)||uniquePick(banks.story,seed+i*17,usedText)||uniquePick(topics,seed+i*19,usedText);
      if(!txt){i++;continue;}
      const handle=uniqueHandle(visitor?rivalHandles:handles,seed+i*11,usedHandles);
      usedText.add(txt); usedHandles.add(handle); rows.push(visitor?[handle,txt,visitor]:[handle,txt]); i++;
    }
    return {rows,p};
  }
  function traffic(p,count){ return p.reaction==='upset-loss'?`🔥 MELTDOWN · ${count} shown`:p.heat===5?`🔥 BIG-MATCH THREAD · ${count} shown`:p.heat===4?`HIGH TRAFFIC · ${count} shown`:`${count} shown`; }
  function render(a){
    const {rows,p}=rowsFor(a), base=h(a.id);
    return `<section class="fan-comments heat-${p.heat}" data-comments-for="${esc(a.id)}" data-reaction="${esc(p.reaction)}"><div class="fan-comments-head"><div><span>CURVA COMMENTS</span><h3>What the fans are saying</h3></div><small>Fictional comments · ${esc(traffic(p,rows.length))}</small></div><div class="fan-comments-list">${rows.map(([user,txt,visitor],i)=>{const mins=i===0?'just now':`${2+((base+i*7)%54)}m`;const votes=7+((base+i*29)%187);return `<article class="fan-comment${visitor?' visitor-comment':''}${p.reaction==='upset-loss'&&!visitor?' meltdown-comment':''}"><div class="fan-avatar">${esc(user[0].toUpperCase())}</div><div><div class="fan-comment-meta"><strong>@${esc(user)}</strong>${visitor?`<em class="visitor-badge">${esc(visitor)} FAN</em>`:''}<span>${mins}</span></div><p>${esc(txt)}</p><div class="fan-actions"><span>▲ ${votes}</span><span>Reply</span></div></div></article>`;}).join('')}</div></section>`;
  }

  let syncing=false;
  function sync(){
    if(syncing)return; const reader=document.getElementById('readerContent'); if(!reader)return;
    const headline=reader.querySelector('#readerHeadline')?.textContent?.trim(); if(!headline){reader.querySelector('.fan-comments')?.remove();return;}
    const a=(window.NAPOLI_DATA?.articles||[]).find(x=>String(x.headline).trim()===headline); if(!a)return;
    const current=reader.querySelector('.fan-comments'); if(current?.dataset.commentsFor===a.id)return;
    syncing=true; current?.remove(); reader.insertAdjacentHTML('beforeend',render(a)); syncing=false;
  }
  const reader=document.getElementById('readerContent'); if(reader){new MutationObserver(()=>queueMicrotask(sync)).observe(reader,{childList:true,subtree:true});sync();}
  document.addEventListener('click',e=>{if(e.target.closest?.('[data-article]'))requestAnimationFrame(sync);});
  document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest?.('[data-article]'))requestAnimationFrame(sync);});

  const style=document.createElement('style');
  style.textContent=`.fan-comments{margin:0 clamp(20px,7vw,76px) 34px;border-top:4px solid var(--navy);padding-top:22px}.fan-comments.heat-5{border-top-width:6px}.fan-comments-head{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:8px}.fan-comments-head span{display:block;color:var(--blue);font-size:.68rem;font-weight:950;letter-spacing:.11em;text-transform:uppercase}.fan-comments-head h3{margin:3px 0 0;font-size:1.35rem;letter-spacing:-.02em}.fan-comments-head small{color:var(--muted);font-size:.7rem;white-space:nowrap;font-weight:800}.fan-comment{display:grid;grid-template-columns:38px 1fr;gap:12px;padding:16px 0;border-bottom:1px solid var(--line)}.fan-avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:var(--navy);color:var(--sky);font-weight:950}.fan-comment-meta{display:flex;gap:8px;align-items:baseline;flex-wrap:wrap}.fan-comment-meta strong{font-size:.84rem;color:var(--navy)}.fan-comment-meta span,.fan-actions{font-size:.68rem;color:var(--muted)}.visitor-badge{font-style:normal;font-size:.57rem;font-weight:950;letter-spacing:.06em;padding:2px 5px;border:1px solid var(--line);border-radius:3px;color:var(--muted);background:#fff}.visitor-comment{background:linear-gradient(90deg,rgba(8,26,45,.035),transparent 62%);margin-left:-10px;margin-right:-10px;padding-left:10px;padding-right:10px}.meltdown-comment p{font-weight:650}.fan-comments[data-reaction="upset-loss"] .fan-comments-head small{color:#9d1c1c}.fan-comment p{margin:4px 0 7px!important;font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important;font-size:.9rem!important;line-height:1.45!important;color:var(--ink)!important}.fan-actions{display:flex;gap:15px;font-weight:800}@media(max-width:760px){.fan-comments{margin:0 20px 24px}.fan-comments-head{align-items:flex-start;flex-direction:column;gap:4px}.fan-comments-head small{white-space:normal}.fan-comment{grid-template-columns:34px 1fr}.fan-avatar{width:34px;height:34px}.visitor-comment{margin-left:-6px;margin-right:-6px;padding-left:6px;padding-right:6px}}@media(max-width:390px){.fan-comments{margin-left:16px;margin-right:16px}}`;
  document.head.appendChild(style);
})();